# -*- coding: utf-8 -*-
"""internal.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qhKCa9SB5QmixnNIDQbq3e_YEdFvq6lH
"""

#Get 10 students data with respective name, age, dob, weight and height. 
#i) Find the BMI (Body Mass Index) and health status. 
#* Health status as categorial data. (Underweight, overweight, healthy)
#task-4
import pandas as pd
data = {
"name": ['suresh', 'vani', 'karthick', 'kalai', 'kumar', 'sudhan', 'dhina', 'sangeetha', 'ramesh', 'surya'],
"date": [2005, 2002, 2002, 2010, 2000, 2009, 2010, 2012, 2013, 2015,],
"weigh": ['60kg', '70kg', '50kg', '45kg', '60kg', '80kg', '30kg', '20kg', '20kg', '40kg',],
"height": ['120cm', '100cm', '80cm', '60cm', '90cm', '80cm', '60cm', '130cm', '175cm', '165cm',]
}
df=pd.DataFrame(data)
df['age']=2022-df['date']
df['health status']=df['age'].apply (lambda X:'underweigh' if X>20 else 'over weigh')
print (df)

#task-1
print('''I am signing up for Replit's 100 days of Python challenge! I will make sure to spend
some time every day coding along, for a minimum of 10 minutes a day. I'll be using
Replit, an amazing online IDE so I can do this from my phone wherever I happend to be.
No excuses for not coding from the middle of a field!''')

#task-2
a=12300
b=(a*18)/100
net_price=a+b
print("Bill\n\n")
print("cost of the mobile\t:\t",a)
print("GST of 18% to mobile\t:\t",b)
print("Net price of the mobile\t",net_price)
print("\t\t\t\t\t\t")

#task-3